# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = app/db/migrations

# template for migration file names, e.g. "%%(rev)s_%%(slug)s.py"
file_template = %%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present.
# defaults to the current working directory.
# prepend_sys_path = .

# timezone in which to execute the migration script
# timezone = UTC

# title of migration when using autogenerate
# revision_environment = false

# set to 'true' to allow .pyc and .pyo files without a source .py file
# sourceless = false

# will be prepended to the database URL in alembic.ini
# prefix_url_with_root_path = true

# version location specification
# version_locations = %(here)s/bar %%(here)s/baz

# the output encoding used when revision files are written
# output_encoding = utf-8

sqlalchemy.url = postgresql+psycopg://user:password@db:5432/app


[post_write_hooks]
# post_write_hooks = ruff,black
# ruff.type = exec
# ruff.entrypoint = ruff
# ruff.options = -q --fix %(path)s
# black.type = exec
# black.entrypoint = black
# black.options = %(path)s


# Logging configuration

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %%(levelname)-5.5s [%%(name)s] %%(message)s
datefmt = %%H:%%M:%%S
